name: PR - Build / Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake lcov

      - name: Configure CMake (with coverage)
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="--coverage" -DCMAKE_C_FLAGS="--coverage"

      - name: Build
        run: cmake --build build --config Debug

      - name: Run tests
        run: ctest --test-dir build --output-on-failure

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ctest-results
          path: build/Testing

      - name: Show test summary
        if: always()
        run: |
          echo "## Test Results" >> $GITHUB_STEP_SUMMARY
          ctest --test-dir build --output-on-failure >> $GITHUB_STEP_SUMMARY

      - name: Generate coverage report
        run: |
          lcov --rc geninfo_unexecuted_blocks=1 --capture --directory build --output-file coverage.info
          lcov --rc geninfo_unexecuted_blocks=1 --remove coverage.info '/usr/*' --output-file coverage.info
          genhtml coverage.info --output-directory coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
